name: python CI 

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

env:
  SERVICE_NAME: julio0619/python-ci

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: python ejercicio.py
  
  build_dockerhub:
    name: Build application on dockerhub
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.SERVICE_NAME }}

  deploy_server:
    name: Deploy application to the server
    needs: [build_dockerhub]
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          username: ${{ secret.SSH_USERNAME }}
          password: ${{ secret.SSH_PASSWORD }}
          port: ${{ secret_PORT }}
          script_stop: true
          script: |
            cd /infra/docker
            docker-compose -f pythonci.yaml pull
            docker-compose -f pythonci.yaml up -d

            


  
